{
  "uid" : "61b7204f3bc2c4b5",
  "name" : "test_multiplication[range_right_error]",
  "fullName" : "test_pytest.test_pytest_task_two.test_task_two.TestTaskTwo#test_multiplication",
  "historyId" : "314eef91d7f19667f8bda7a10de39cc5",
  "time" : {
    "start" : 1611106819940,
    "stop" : 1611106819941,
    "duration" : 1
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: 计算结果大于区间\nassert (10.1 >= 5 and 10.1 <= 10)",
  "statusTrace" : "self = <test_task_two.TestTaskTwo object at 0x0000029AE22C6048>, a = 1, b = 10.1, range_left = 5, range_right = 10, setup_teardown = None\n\n    @allure.story(\"乘法运算用例\")\n    @pytest.mark.run(order=4)\n    # @pytest.mark.usefixtures(\"setup_teardown\")\n    @pytest.mark.parametrize(\"a,b,range_left,range_right\", get_yaml_data(key=\"multiplication\"), ids=get_yaml_data(key=\"ids\"))\n    def test_multiplication(self,a,b,range_left,range_right,setup_teardown):\n        r = Calculator.multiplication(a, b)\n        if isinstance(r, float):\n            r = round(r, 2)\n        with allure.step(\"断言\"):\n>           assert (r >= range_left and r <= range_right), \"计算结果小于区间\" if r < range_left else \"计算结果大于区间\" if r > range_left else r\nE           AssertionError: 计算结果大于区间\nE           assert (10.1 >= 5 and 10.1 <= 10)\n\ntest_pytest\\test_pytest_task_two\\test_task_two.py:47: AssertionError",
  "flaky" : true,
  "beforeStages" : [ {
    "name" : "setup_teardown",
    "time" : {
      "start" : 1611106789520,
      "stop" : 1611106789520,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: 计算结果大于区间\nassert (10.1 >= 5 and 10.1 <= 10)",
    "statusTrace" : "self = <test_task_two.TestTaskTwo object at 0x0000029AE22C6048>, a = 1, b = 10.1, range_left = 5, range_right = 10, setup_teardown = None\n\n    @allure.story(\"乘法运算用例\")\n    @pytest.mark.run(order=4)\n    # @pytest.mark.usefixtures(\"setup_teardown\")\n    @pytest.mark.parametrize(\"a,b,range_left,range_right\", get_yaml_data(key=\"multiplication\"), ids=get_yaml_data(key=\"ids\"))\n    def test_multiplication(self,a,b,range_left,range_right,setup_teardown):\n        r = Calculator.multiplication(a, b)\n        if isinstance(r, float):\n            r = round(r, 2)\n        with allure.step(\"断言\"):\n>           assert (r >= range_left and r <= range_right), \"计算结果小于区间\" if r < range_left else \"计算结果大于区间\" if r > range_left else r\nE           AssertionError: 计算结果大于区间\nE           assert (10.1 >= 5 and 10.1 <= 10)\n\ntest_pytest\\test_pytest_task_two\\test_task_two.py:47: AssertionError",
    "steps" : [ {
      "name" : "断言",
      "time" : {
        "start" : 1611106819940,
        "stop" : 1611106819940,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: 计算结果大于区间\nassert (10.1 >= 5 and 10.1 <= 10)\n",
      "statusTrace" : "  File \"C:\\Users\\余伟豪\\Desktop\\PythonDemo\\test_pytest\\test_pytest_task_two\\test_task_two.py\", line 47, in test_multiplication\n    assert (r >= range_left and r <= range_right), \"计算结果小于区间\" if r < range_left else \"计算结果大于区间\" if r > range_left else r\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "hasContent" : true,
      "shouldDisplayMessage" : true,
      "attachmentsCount" : 0
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 0
  },
  "afterStages" : [ {
    "name" : "setup_teardown::0",
    "time" : {
      "start" : 1611106819957,
      "stop" : 1611106819957,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "story",
    "value" : "乘法运算用例"
  }, {
    "name" : "feature",
    "value" : "作业二"
  }, {
    "name" : "tag",
    "value" : "run(order=4)"
  }, {
    "name" : "parentSuite",
    "value" : "test_pytest.test_pytest_task_two"
  }, {
    "name" : "suite",
    "value" : "test_task_two"
  }, {
    "name" : "subSuite",
    "value" : "TestTaskTwo"
  }, {
    "name" : "host",
    "value" : "DESKTOP-939OH2V"
  }, {
    "name" : "thread",
    "value" : "6820-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_pytest.test_pytest_task_two.test_task_two"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "a",
    "value" : "1"
  }, {
    "name" : "b",
    "value" : "10.1"
  }, {
    "name" : "range_left",
    "value" : "5"
  }, {
    "name" : "range_right",
    "value" : "10"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "5f9841ef79c961c8",
      "status" : "failed",
      "statusDetails" : "AssertionError: 计算结果大于区间\nassert (10.1 >= 5 and 10.1 <= 10)",
      "time" : {
        "start" : 1611106741559,
        "stop" : 1611106741559,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "run(order=4)" ]
  },
  "source" : "61b7204f3bc2c4b5.json",
  "parameterValues" : [ "1", "10.1", "5", "10" ]
}